### ISSUE TITLE
UnicodeDecodeError in part of my files

### ISSUE THREAD

**Issue by loukiaspi** [willros/bam2plot#5]
Hi, 
I am trying to run bam2plot for a series of bam files from different species and while for some it works perfectly well, for others I get the following error:

Traceback (most recent call last):
  File "/ceph/users/lspilani/.conda/envs/mapping/bin/bam2plot", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/bam2plot/main.py", line 296, in run
    fire.Fire(cli)
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/bam2plot/main.py", line 207, in cli
    perbase = run_perbase(bam)
              ^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/mapping/lib/python3.12/site-packages/bam2plot/main.py", line 55, in run_perbase
    ).decode()
      ^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 3668593876: invalid start byte

All my files have been processed in the same way and the only difference between them is the reference genome that they have been mapped against, but I can't see how this would interfere with bam2plot. Do you have any ideas? I am [sending](https://www.dropbox.com/scl/fi/teqpul0d23253lwxoqc3h/failed_samples.zip?rlkey=e9lwag2ffvf9c60x3g2n1fs9i&dl=0) you one of the flies that failed in case you want to check for reproducibility

**Comment by willros** [comment]
Hi,

I downloaded the example file that you've provided, and it works perfectly fine for me. 

Thanks,
William

**Comment by loukiaspi** [comment]
In this case, would you mind sharing the list of packages in your environment and their versions? maybe by replicating that, I will sort out my error

**Comment by willros** [comment]
I installed `bam2plot` fresh in a new environment and runned it. Can you try it again and see if it still crashes?


I will look into it in more detail later.

**Comment by loukiaspi** [comment]
I tried it again with a fresh installation of everything and I still get the same error for the same individuals

**Comment by willros** [comment]
I have updated the package and pushed it to pip.

Try install the latest version and run it again. 

I also added `--log_scale` if you want the depth to be on a log scale.

Let me know if it works!
William

**Comment by loukiaspi** [comment]
Hi William,

Thank you for looking into this! I used the new version and it does work but I am getting a new error in some of the files. It has been able to generate plots for all my files (which was not the case before) but now in some of them, it generates plots for some of the chromosomes/contigs and at some point it gives me the following error:

Traceback (most recent call last):
  File "/ceph/users/lspilani/.conda/envs/bam2plot/bin/bam2plot", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 307, in run
    fire.Fire(cli)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 270, in cli
    print_coverage_info(mpileup_df, threshold)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 72, in print_coverage_info
    name = df.iloc[0].id
           ~~~~~~~^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/pandas/core/indexing.py", line 1752, in _getitem_axis
    self._validate_integer(key, axis)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/pandas/core/indexing.py", line 1685, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

After this error it just "jumps" to the next file (I am looping through all of my files). Given that it does not happen for all of my files, I am including one of the [problematic ones](https://www.dropbox.com/scl/fi/pcd62jm5d1mngxc7wk732/IndexerOutOfBoundsError.zip?rlkey=omnhb7n8jwxgrt3io6fge1gkm&dl=0), in case it's helpful. For this file, it gave me the error after producing the plot for "contig_ChrW_unloc_9"

**Comment by willros** [comment]
Try again now with a new installment.

**Comment by loukiaspi** [comment]
After updating I get this error for every file:

Traceback (most recent call last):
  File "/ceph/users/lspilani/.conda/envs/bam2plot/bin/bam2plot", line 5, in <module>
    from bam2plot.main import run
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 4, in <module>
    import pysam
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: libdeflate.so.0: cannot open shared object file: No such file or directory

**Comment by willros** [comment]
That is a problem with pysam. That is strange, since that have not changed. 

Which version of pysam are you using and what os?

**Comment by loukiaspi** [comment]
my pysam version is 0.22.0 and I am working at my uni's cluster that runs on Debian GNU/Linux 9 (stretch)

**Comment by willros** [comment]
try  conda install -c conda-forge -c bioconda libdeflate=1.8

**Comment by loukiaspi** [comment]
it looks like all of the plots for all the chromosomes/contigs/individuals were plotted without errors, thank you!!
