### ISSUE TITLE
feature suggestion: option to create only svg or png, not both

### ISSUE THREAD

**Issue by loukiaspi** [willros/bam2plot#7]
I'm opening a different issue for this, in order to not mix up two totally different topics...

so, I was wondering if there's a way to add an option to only produce either svg or png plots? I don't need both every time so it would be nice to be able to choose in advance instead of deleting afterwards

**Comment by willros** [comment]
Nice suggestion.

I have added `-p` option. choose between png, svg or both.

Install the latest and try again!

What do you think about the recent changes? How everything is reported in the terminal etc?
Thanks!
Ville

**Comment by willros** [comment]
I have updated everything again. I changed pandas to polars and fixed some bugs in how everything was reported. Now its working faster and better!

**Comment by loukiaspi** [comment]
although I have all my plots, I made a new environment and re-installed bam2plot just to see if it would run for me and first I got the same error as yesterday which was solved by following the advice that you gave me then (conda install -c conda-forge -c bioconda libdeflate=1.8) and then I got a new error:

Traceback (most recent call last):
  File "/ceph/users/lspilani/.conda/envs/bam2plot/bin/bam2plot", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 333, in cli
    main(
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 467, in main
    perbase = if_sort_and_index(sort_and_index, index, bam)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 351, in if_sort_and_index
    return run_perbase(bam)
           ^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 74, in run_perbase
    subprocess.check_output(
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'perbase only-depth Agl_ichnusa_RV11E500_vs_905147175_2_ilAglUrti1_2.RD.bam' returned non-zero exit status 1.

**Comment by willros** [comment]
you need to install perbase:
```console
conda install -c bioconda perbase
```
or via cargo:
```console
cargo install perbase
```

**Comment by loukiaspi** [comment]
I actually have perbase installed in this new environment and I still get this error, I have version 0.1.0, should it be something different?

**Comment by loukiaspi** [comment]
I tried bam2plot v 0.2.7, 0.2.8 and 0.2.9 and the last two don't work giving me the same error I mentioned above. Same environment, I was only downgrading bam2plot. I don't know if this helps in any way

**Comment by loukiaspi** [comment]
I re-did everything because it was bugging me, I now have prebase 0.9.0 and I had to install pyarrow bc I got a relevant error and it seems to be running ok again 👌

**Comment by loukiaspi** [comment]
I spoke too soon, the new version runs on some of the samples without errors, while on others I get a warning of this type: 

/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py:409: UserWarning: Glyph 0 (^@) missing from current font.
  plot.savefig(f"{name}.png")
/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py:409: UserWarning: Glyph 4 (^D) missing from current font.
  plot.savefig(f"{name}.png")
/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py:409: UserWarning: Glyph 20 (^T) missing from current font.
  plot.savefig(f"{name}.png")


And for the samples for which I get the warning, I also get the following error and no plot is produced:


Traceback (most recent call last):
  File "/ceph/users/lspilani/.conda/envs/bam2plot/bin/bam2plot", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 333, in cli
    main(
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 514, in main
    save_plot_coverage(plot, outpath, sample_name, reference, plot_type)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/bam2plot/main.py", line 409, in save_plot_coverage
    plot.savefig(f"{name}.png")
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/ceph/users/lspilani/.conda/envs/bam2plot/lib/python3.12/site-packages/PIL/Image.py", line 2436, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: embedded null byte

**Comment by willros** [comment]
Seems like you have an issue with the naming of the reference sequences... Not sure about that.
