### ISSUE TITLE
local variable 'df' referenced before assignment

### ISSUE THREAD

**Issue by MikeWLloyd** [willros/bam2plot#8]
I am encountering the following error: 

```
[ERROR]: Could not process dataframe
Traceback (most recent call last):
  File "/home/lloydm/.local/bin/bam2plot", line 8, in <module>
    sys.exit(cli())
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 346, in cli
    main(
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 482, in main
    df = process_dataframe(perbase, sort_and_index, index, threshold)
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 414, in process_dataframe
    return df
UnboundLocalError: local variable 'df' referenced before assignment
```

Can you provide any guidance on troubleshooting this one?

**Comment by willros** [comment]
Try pip install the latest version, 0.3.1

**Comment by MikeWLloyd** [comment]
I just changed to 0.3.1, and now see: 

```
[INFO]: Sorting bam file
[INFO]: Indexing bam file
[INFO]: Indexing bam file
[INFO]: Processing dataframe
[ERROR]: Could not process dataframe
```

**Comment by willros** [comment]
Pushed another one, 0.3.2

Install that and see what the error message is.

I think there is a problem with your bam file.

**Comment by MikeWLloyd** [comment]
Will try. Does the tool expect `chr` in the names? or something along those lines that I could be missing?

**Comment by MikeWLloyd** [comment]
```
[ERROR]: Could not process dataframe: could not parse `MT` as dtype `i64` at column 'REF' (column number 1)

The current offset in the file is 593696497 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `MT` to the `null_values` list.

Original error: ```remaining bytes non-empty```
Traceback (most recent call last):
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 399, in process_dataframe
    df = perbase_to_df(perbase, threshold)
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 84, in perbase_to_df
    pl.read_csv(perbase, separator="\t")
  File "/home/lloydm/.local/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
  File "/home/lloydm/.local/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
  File "/home/lloydm/.local/lib/python3.9/site-packages/polars/_utils/deprecation.py", line 134, in wrapper
    return function(*args, **kwargs)
  File "/home/lloydm/.local/lib/python3.9/site-packages/polars/io/csv/functions.py", line 397, in read_csv
    df = pl.DataFrame._read_csv(
  File "/home/lloydm/.local/lib/python3.9/site-packages/polars/dataframe/frame.py", line 749, in _read_csv
    self._df = PyDataFrame.read_csv(
polars.exceptions.ComputeError: could not parse `MT` as dtype `i64` at column 'REF' (column number 1)

The current offset in the file is 593696497 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `dtypes` argument
- setting `ignore_errors` to `True`,
- adding `MT` to the `null_values` list.

Original error: ```remaining bytes non-empty```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lloydm/.local/bin/bam2plot", line 8, in <module>
    sys.exit(cli())
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 348, in cli
    main(
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 475, in main
    df = process_dataframe(perbase, sort_and_index, index, threshold)
  File "/home/lloydm/.local/lib/python3.9/site-packages/bam2plot/main.py", line 407, in process_dataframe
    raise RuntimeError("Dataframe processing failed due to an error.") from e
RuntimeError: Dataframe processing failed due to an error.
```

**Comment by willros** [comment]
Now it should work.

**Comment by MikeWLloyd** [comment]
Hit a missing requirement, but otherwise your update fixed things. Thanks! 

```
ModuleNotFoundError: No module named 'pyarrow'
```
